-- =============================================================================
-- SISTEMA DE MICROMEDIÇÃO AUTOMATIZADA
-- Script de Carga Inicial de Dados
--
-- Autor: Sistema de Micromedição
-- Versão: 1.0
-- Data: 2025
-- =============================================================================

-- Limpar dados existentes (se houver)
DELETE FROM TB_MEASUREMENTS;
DELETE FROM TB_MICROSCOPY_IMAGES;
DELETE FROM TB_SAMPLES;
DELETE FROM TB_DIGITAL_MICROSCOPES;
DELETE FROM TB_OPERATORS;

-- Reset das sequences
ALTER SEQUENCE SQ_OPERATORS RESTART START WITH 1;
ALTER SEQUENCE SQ_DIGITAL_MICROSCOPES RESTART START WITH 1;
ALTER SEQUENCE SQ_SAMPLES RESTART START WITH 1;
ALTER SEQUENCE SQ_MICROSCOPY_IMAGES RESTART START WITH 1;
ALTER SEQUENCE SQ_MEASUREMENTS RESTART START WITH 1;

-- =============================================================================
-- CARGA DE DADOS - OPERADORES
-- =============================================================================

INSERT INTO TB_OPERATORS (ID, OPERATOR_ID, NOME, EMAIL, NIVEL_ACESSO, DATA_CRIACAO, ATIVO)
VALUES (SQ_OPERATORS.NEXTVAL, 'OP001', 'Dr. João Silva', 'joao.silva@hospital.com.br', 'ADMIN', SYSDATE, 'S');

INSERT INTO TB_OPERATORS (ID, OPERATOR_ID, NOME, EMAIL, NIVEL_ACESSO, DATA_CRIACAO, ATIVO)
VALUES (SQ_OPERATORS.NEXTVAL, 'OP002', 'Maria Santos', 'maria.santos@hospital.com.br', 'TECNICO', SYSDATE, 'S');

INSERT INTO TB_OPERATORS (ID, OPERATOR_ID, NOME, EMAIL, NIVEL_ACESSO, DATA_CRIACAO, ATIVO)
VALUES (SQ_OPERATORS.NEXTVAL, 'OP003', 'Carlos Oliveira', 'carlos.oliveira@hospital.com.br', 'OPERADOR', SYSDATE, 'S');

INSERT INTO TB_OPERATORS (ID, OPERATOR_ID, NOME, EMAIL, NIVEL_ACESSO, DATA_CRIACAO, ATIVO)
VALUES (SQ_OPERATORS.NEXTVAL, 'OP004', 'Ana Costa', 'ana.costa@hospital.com.br', 'TECNICO', SYSDATE, 'S');

INSERT INTO TB_OPERATORS (ID, OPERATOR_ID, NOME, EMAIL, NIVEL_ACESSO, DATA_CRIACAO, ATIVO)
VALUES (SQ_OPERATORS.NEXTVAL, 'OP005', 'Pedro Almeida', 'pedro.almeida@hospital.com.br', 'OPERADOR', SYSDATE, 'S');

-- =============================================================================
-- CARGA DE DADOS - MICROSCÓPIOS DIGITAIS
-- =============================================================================

INSERT INTO TB_DIGITAL_MICROSCOPES (
    ID, MICROSCOPE_ID, MODELO, FABRICANTE, NUMERO_SERIE,
    MAGNIFICACAO_MAXIMA, ESCALA_PIXELS_UM, RESOLUCAO_MAXIMA,
    DATA_AQUISICAO, STATUS, OBSERVACOES, DATA_CRIACAO
) VALUES (
    SQ_DIGITAL_MICROSCOPES.NEXTVAL, 'MICRO001', 'DM6000B', 'Leica', 'LM001234567',
    1000.0, 10.0, '1920x1080', DATE '2023-01-15', 'ATIVO',
    'Microscópio principal do laboratório de patologia', SYSDATE
);

INSERT INTO TB_DIGITAL_MICROSCOPES (
    ID, MICROSCOPE_ID, MODELO, FABRICANTE, NUMERO_SERIE,
    MAGNIFICACAO_MAXIMA, ESCALA_PIXELS_UM, RESOLUCAO_MAXIMA,
    DATA_AQUISICAO, STATUS, OBSERVACOES, DATA_CRIACAO
) VALUES (
    SQ_DIGITAL_MICROSCOPES.NEXTVAL, 'MICRO002', 'BX53', 'Olympus', 'OL987654321',
    400.0, 8.5, '1280x960', DATE '2023-06-20', 'ATIVO',
    'Microscópio secundário para análises rápidas', SYSDATE
);

INSERT INTO TB_DIGITAL_MICROSCOPES (
    ID, MICROSCOPE_ID, MODELO, FABRICANTE, NUMERO_SERIE,
    MAGNIFICACAO_MAXIMA, ESCALA_PIXELS_UM, RESOLUCAO_MAXIMA,
    DATA_AQUISICAO, STATUS, OBSERVACOES, DATA_CRIACAO
) VALUES (
    SQ_DIGITAL_MICROSCOPES.NEXTVAL, 'MICRO003', 'Axio Imager', 'Zeiss', 'ZE555888999',
    1500.0, 12.0, '2048x1536', DATE '2022-11-10', 'MANUTENCAO',
    'Em manutenção preventiva - previsão de retorno em 1 semana', SYSDATE
);

-- =============================================================================
-- CARGA DE DADOS - AMOSTRAS
-- =============================================================================

INSERT INTO TB_SAMPLES (
    ID, SAMPLE_ID, NOME, TIPO, DATA_COLETA, OPERADOR_RESPONSAVEL,
    DESCRICAO, PACIENTE_ID, LOCALIZACAO_ANATOMICA, METODO_PREPARACAO,
    DATA_CRIACAO, STATUS
) VALUES (
    SQ_SAMPLES.NEXTVAL, 'SAMPLE_001', 'Sangue Paciente A', 'Sangue',
    TO_DATE('2024-01-15 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Dr. João Silva',
    'Amostra de sangue coletada para análise de eritrócitos',
    'PAC001', 'Veia antecubital', 'Esfregaço em lâmina com coloração Giemsa',
    SYSDATE, 'ATIVA'
);

INSERT INTO TB_SAMPLES (
    ID, SAMPLE_ID, NOME, TIPO, DATA_COLETA, OPERADOR_RESPONSAVEL,
    DESCRICAO, PACIENTE_ID, LOCALIZACAO_ANATOMICA, METODO_PREPARACAO,
    DATA_CRIACAO, STATUS
) VALUES (
    SQ_SAMPLES.NEXTVAL, 'SAMPLE_002', 'Tecido Muscular', 'Tecido',
    TO_DATE('2024-01-15 09:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Maria Santos',
    'Biópsia de tecido muscular para análise histopatológica',
    'PAC002', 'Músculo deltóide', 'Fixação em formalina e corte histológico',
    SYSDATE, 'ATIVA'
);

INSERT INTO TB_SAMPLES (
    ID, SAMPLE_ID, NOME, TIPO, DATA_COLETA, OPERADOR_RESPONSAVEL,
    DESCRICAO, PACIENTE_ID, LOCALIZACAO_ANATOMICA, METODO_PREPARACAO,
    DATA_CRIACAO, STATUS
) VALUES (
    SQ_SAMPLES.NEXTVAL, 'SAMPLE_003', 'Célula Neural', 'Neurônio',
    TO_DATE('2024-01-15 15:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Carlos Oliveira',
    'Cultura de neurônios para estudo de morfologia celular',
    'PAC003', 'Córtex cerebral', 'Cultura celular em meio DMEM',
    SYSDATE, 'ATIVA'
);

INSERT INTO TB_SAMPLES (
    ID, SAMPLE_ID, NOME, TIPO, DATA_COLETA, OPERADOR_RESPONSAVEL,
    DESCRICAO, PACIENTE_ID, LOCALIZACAO_ANATOMICA, METODO_PREPARACAO,
    DATA_CRIACAO, STATUS
) VALUES (
    SQ_SAMPLES.NEXTVAL, 'SAMPLE_004', 'Tecido Hepático', 'Tecido',
    TO_DATE('2024-01-16 10:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ana Costa',
    'Biópsia hepática para análise de hepatócitos',
    'PAC004', 'Lóbulo hepático', 'Fixação e processamento histológico padrão',
    SYSDATE, 'PROCESSADA'
);

INSERT INTO TB_SAMPLES (
    ID, SAMPLE_ID, NOME, TIPO, DATA_COLETA, OPERADOR_RESPONSAVEL,
    DESCRICAO, PACIENTE_ID, LOCALIZACAO_ANATOMICA, METODO_PREPARACAO,
    DATA_CRIACAO, STATUS
) VALUES (
    SQ_SAMPLES.NEXTVAL, 'SAMPLE_005', 'Células Epiteliais', 'Epitélio',
    TO_DATE('2024-01-16 14:20:00', 'YYYY-MM-DD HH24:MI:SS'), 'Pedro Almeida',
    'Raspado de mucosa bucal para análise citológica',
    'PAC005', 'Mucosa bucal', 'Raspado e fixação em álcool 70%',
    SYSDATE, 'ATIVA'
);

-- =============================================================================
-- CARGA DE DADOS - IMAGENS MICROSCÓPICAS
-- =============================================================================

INSERT INTO TB_MICROSCOPY_IMAGES (
    ID, IMAGE_ID, SAMPLE_ID_FK, MICROSCOPE_ID_FK, ARQUIVO,
    FORMATO, TAMANHO_BYTES, RESOLUCAO, MAGNIFICACAO,
    DATA_CAPTURA, OPERADOR_CAPTURA, OBSERVACOES, DATA_CRIACAO
) VALUES (
    SQ_MICROSCOPY_IMAGES.NEXTVAL, 'IMG_1749780022', 1, 1, 'IMG_1749780022.jpg',
    'JPG', 2048576, '1920x1080', 400.0,
    TO_DATE('2024-01-15 10:30:22', 'YYYY-MM-DD HH24:MI:SS'), 'Dr. João Silva',
    'Imagem de eritrócitos com boa definição', SYSDATE
);

INSERT INTO TB_MICROSCOPY_IMAGES (
    ID, IMAGE_ID, SAMPLE_ID_FK, MICROSCOPE_ID_FK, ARQUIVO,
    FORMATO, TAMANHO_BYTES, RESOLUCAO, MAGNIFICACAO,
    DATA_CAPTURA, OPERADOR_CAPTURA, OBSERVACOES, DATA_CRIACAO
) VALUES (
    SQ_MICROSCOPY_IMAGES.NEXTVAL, 'IMG_1749950847', 2, 1, 'IMG_1749950847.jpg',
    'JPG', 3145728, '1920x1080', 200.0,
    TO_DATE('2024-01-15 11:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'Maria Santos',
    'Tecido muscular com fibras bem preservadas', SYSDATE
);

INSERT INTO TB_MICROSCOPY_IMAGES (
    ID, IMAGE_ID, SAMPLE_ID_FK, MICROSCOPE_ID_FK, ARQUIVO,
    FORMATO, TAMANHO_BYTES, RESOLUCAO, MAGNIFICACAO,
    DATA_CAPTURA, OPERADOR_CAPTURA, OBSERVACOES, DATA_CRIACAO
) VALUES (
    SQ_MICROSCOPY_IMAGES.NEXTVAL, 'IMG_1749951001', 3, 2, 'IMG_1749951001.jpg',
    'JPG', 1572864, '1280x960', 600.0,
    TO_DATE('2024-01-15 16:10:00', 'YYYY-MM-DD HH24:MI:SS'), 'Carlos Oliveira',
    'Neurônios com dendritos visíveis', SYSDATE
);

INSERT INTO TB_MICROSCOPY_IMAGES (
    ID, IMAGE_ID, SAMPLE_ID_FK, MICROSCOPE_ID_FK, ARQUIVO,
    FORMATO, TAMANHO_BYTES, RESOLUCAO, MAGNIFICACAO,
    DATA_CAPTURA, OPERADOR_CAPTURA, OBSERVACOES, DATA_CRIACAO
) VALUES (
    SQ_MICROSCOPY_IMAGES.NEXTVAL, 'IMG_1749951695', 4, 1, 'IMG_1749951695.jpg',
    'JPG', 2621440, '1920x1080', 400.0,
    TO_DATE('2024-01-16 11:20:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ana Costa',
    'Hepatócitos com núcleo central bem definido', SYSDATE
);

INSERT INTO TB_MICROSCOPY_IMAGES (
    ID, IMAGE_ID, SAMPLE_ID_FK, MICROSCOPE_ID_FK, ARQUIVO,
    FORMATO, TAMANHO_BYTES, RESOLUCAO, MAGNIFICACAO,
    DATA_CAPTURA, OPERADOR_CAPTURA, OBSERVACOES, DATA_CRIACAO
) VALUES (
    SQ_MICROSCOPY_IMAGES.NEXTVAL, 'IMG_1749951957', 5, 2, 'IMG_1749951957.jpg',
    'JPG', 1310720, '1280x960', 200.0,
    TO_DATE('2024-01-16 15:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Pedro Almeida',
    'Células epiteliais descamativas', SYSDATE
);

-- =============================================================================
-- CARGA DE DADOS - MEDIÇÕES
-- =============================================================================

INSERT INTO TB_MEASUREMENTS (
    ID, MEASUREMENT_ID, SAMPLE_ID_FK, IMAGE_ID_FK, MICROSCOPE_ID_FK, OPERATOR_ID_FK,
    AREA_PIXELS, AREA_MICROMETERS, SCALE_PIXELS_PER_UM, DATA_MEDICAO,
    METODO_PROCESSAMENTO, PARAMETROS_PROCESSAMENTO, OBSERVACOES,
    VALIDADA, DATA_VALIDACAO, OPERADOR_VALIDACAO, DATA_CRIACAO
) VALUES (
    SQ_MEASUREMENTS.NEXTVAL, 'MEAS_1749780022', 1, 1, 1, 1,
    23929, 239.29, 10.0, TO_DATE('2024-01-15 10:30:22', 'YYYY-MM-DD HH24:MI:SS'),
    'OpenCV Threshold + Contour Detection',
    '{"threshold": 120, "blur_kernel": 5, "min_area": 500}',
    'Medição automática de eritrócitos', 'S',
    TO_DATE('2024-01-15 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Dr. João Silva', SYSDATE
);

INSERT INTO TB_MEASUREMENTS (
    ID, MEASUREMENT_ID, SAMPLE_ID_FK, IMAGE_ID_FK, MICROSCOPE_ID_FK, OPERATOR_ID_FK,
    AREA_PIXELS, AREA_MICROMETERS, SCALE_PIXELS_PER_UM, DATA_MEDICAO,
    METODO_PROCESSAMENTO, PARAMETROS_PROCESSAMENTO, OBSERVACOES,
    VALIDADA, DATA_VALIDACAO, OPERADOR_VALIDACAO, DATA_CRIACAO
) VALUES (
    SQ_MEASUREMENTS.NEXTVAL, 'MEAS_1749950847', 2, 2, 1, 2,
    301661, 3016.61, 10.0, TO_DATE('2024-01-15 11:45:00', 'YYYY-MM-DD HH24:MI:SS'),
    'OpenCV Threshold + Contour Detection',
    '{"threshold": 115, "blur_kernel": 5, "min_area": 800}',
    'Área total de fibras musculares', 'S',
    TO_DATE('2024-01-15 12:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'Maria Santos', SYSDATE
);

INSERT INTO TB_MEASUREMENTS (
    ID, MEASUREMENT_ID, SAMPLE_ID_FK, IMAGE_ID_FK, MICROSCOPE_ID_FK, OPERATOR_ID_FK,
    AREA_PIXELS, AREA_MICROMETERS, SCALE_PIXELS_PER_UM, DATA_MEDICAO,
    METODO_PROCESSAMENTO, PARAMETROS_PROCESSAMENTO, OBSERVACOES,
    VALIDADA, DATA_VALIDACAO, OPERADOR_VALIDACAO, DATA_CRIACAO
) VALUES (
    SQ_MEASUREMENTS.NEXTVAL, 'MEAS_1749951001', 3, 3, 2, 3,
    302050, 3020.50, 8.5, TO_DATE('2024-01-15 16:10:00', 'YYYY-MM-DD HH24:MI:SS'),
    'OpenCV Threshold + Contour Detection',
    '{"threshold": 125, "blur_kernel": 3, "min_area": 300}',
    'Soma neuronal principal', 'N', NULL, NULL, SYSDATE
);

INSERT INTO TB_MEASUREMENTS (
    ID, MEASUREMENT_ID, SAMPLE_ID_FK, IMAGE_ID_FK, MICROSCOPE_ID_FK, OPERATOR_ID_FK,
    AREA_PIXELS, AREA_MICROMETERS, SCALE_PIXELS_PER_UM, DATA_MEDICAO,
    METODO_PROCESSAMENTO, PARAMETROS_PROCESSAMENTO, OBSERVACOES,
    VALIDADA, DATA_VALIDACAO, OPERADOR_VALIDACAO, DATA_CRIACAO
) VALUES (
    SQ_MEASUREMENTS.NEXTVAL, 'MEAS_1749951695', 4, 4, 1, 4,
    312138, 3121.38, 10.0, TO_DATE('2024-01-16 11:20:00', 'YYYY-MM-DD HH24:MI:SS'),
    'OpenCV Threshold + Contour Detection',
    '{"threshold": 110, "blur_kernel": 5, "min_area": 600}',
    'Área de hepatócitos funcionais', 'S',
    TO_DATE('2024-01-16 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Ana Costa', SYSDATE
);

INSERT INTO TB_MEASUREMENTS (
    ID, MEASUREMENT_ID, SAMPLE_ID_FK, IMAGE_ID_FK, MICROSCOPE_ID_FK, OPERATOR_ID_FK,
    AREA_PIXELS, AREA_MICROMETERS, SCALE_PIXELS_PER_UM, DATA_MEDICAO,
    METODO_PROCESSAMENTO, PARAMETROS_PROCESSAMENTO, OBSERVACOES,
    VALIDADA, DATA_VALIDACAO, OPERADOR_VALIDACAO, DATA_CRIACAO
) VALUES (
    SQ_MEASUREMENTS.NEXTVAL, 'MEAS_1749951957', 5, 5, 2, 5,
    289764, 2897.64, 8.5, TO_DATE('2024-01-16 15:30:00', 'YYYY-MM-DD HH24:MI:SS'),
    'OpenCV Threshold + Contour Detection',
    '{"threshold": 130, "blur_kernel": 5, "min_area": 400}',
    'Células epiteliais descamativas', 'N', NULL, NULL, SYSDATE
);

-- =============================================================================
-- COMMITS E VERIFICAÇÕES
-- =============================================================================

-- Confirma todas as inserções
COMMIT;

-- Verificação dos dados inseridos
SELECT 'OPERADORES: ' || COUNT(*) as TOTAL FROM TB_OPERATORS;
SELECT 'MICROSCÓPIOS: ' || COUNT(*) as TOTAL FROM TB_DIGITAL_MICROSCOPES;
SELECT 'AMOSTRAS: ' || COUNT(*) as TOTAL FROM TB_SAMPLES;
SELECT 'IMAGENS: ' || COUNT(*) as TOTAL FROM TB_MICROSCOPY_IMAGES;
SELECT 'MEDIÇÕES: ' || COUNT(*) as TOTAL FROM TB_MEASUREMENTS;

-- Estatísticas gerais
SELECT
    'DADOS CARREGADOS COM SUCESSO!' as STATUS,
    (SELECT COUNT(*) FROM TB_OPERATORS) as OPERADORES,
    (SELECT COUNT(*) FROM TB_DIGITAL_MICROSCOPES) as MICROSCOPIOS,
    (SELECT COUNT(*) FROM TB_SAMPLES) as AMOSTRAS,
    (SELECT COUNT(*) FROM TB_MICROSCOPY_IMAGES) as IMAGENS,
    (SELECT COUNT(*) FROM TB_MEASUREMENTS) as MEDICOES
FROM DUAL;

-- Verificação de integridade referencial
SELECT
    'VERIFICAÇÃO DE INTEGRIDADE' as TESTE,
    CASE
        WHEN EXISTS (
            SELECT 1 FROM TB_MEASUREMENTS m
            WHERE m.SAMPLE_ID_FK NOT IN (SELECT s.ID FROM TB_SAMPLES s)
        ) THEN 'FALHA'
        ELSE 'OK'
    END as SAMPLE_FK,
    CASE
        WHEN EXISTS (
            SELECT 1 FROM TB_MEASUREMENTS m
            WHERE m.IMAGE_ID_FK NOT IN (SELECT i.ID FROM TB_MICROSCOPY_IMAGES i)
        ) THEN 'FALHA'
        ELSE 'OK'
    END as IMAGE_FK,
    CASE
        WHEN EXISTS (
            SELECT 1 FROM TB_MEASUREMENTS m
            WHERE m.MICROSCOPE_ID_FK NOT IN (SELECT d.ID FROM TB_DIGITAL_MICROSCOPES d)
        ) THEN 'FALHA'
        ELSE 'OK'
    END as MICROSCOPE_FK,
    CASE
        WHEN EXISTS (
            SELECT 1 FROM TB_MEASUREMENTS m
            WHERE m.OPERATOR_ID_FK NOT IN (SELECT o.ID FROM TB_OPERATORS o)
        ) THEN 'FALHA'
        ELSE 'OK'
    END as OPERATOR_FK
FROM DUAL;

-- Exemplos de consultas úteis
SELECT 'CONSULTA: Medições por operador' as EXEMPLO FROM DUAL;
SELECT
    o.NOME as OPERADOR,
    o.NIVEL_ACESSO,
    COUNT(m.ID) as TOTAL_MEDICOES,
    ROUND(AVG(m.AREA_MICROMETERS), 2) as AREA_MEDIA_UM
FROM TB_OPERATORS o
LEFT JOIN TB_MEASUREMENTS m ON o.ID = m.OPERATOR_ID_FK
GROUP BY o.NOME, o.NIVEL_ACESSO
ORDER BY TOTAL_MEDICOES DESC;

SELECT 'CONSULTA: Medições por tipo de amostra' as EXEMPLO FROM DUAL;
SELECT
    s.TIPO as TIPO_AMOSTRA,
    COUNT(m.ID) as TOTAL_MEDICOES,
    ROUND(AVG(m.AREA_MICROMETERS), 2) as AREA_MEDIA_UM,
    ROUND(MIN(m.AREA_MICROMETERS), 2) as AREA_MINIMA_UM,
    ROUND(MAX(m.AREA_MICROMETERS), 2) as AREA_MAXIMA_UM
FROM TB_SAMPLES s
LEFT JOIN TB_MEASUREMENTS m ON s.ID = m.SAMPLE_ID_FK
GROUP BY s.TIPO
ORDER BY TOTAL_MEDICOES DESC;